/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;
import Project.connectionProvider;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saket Saurabh
 */

public class Billing extends javax.swing.JFrame {
    public int finalTotal=0;
    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
       
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyy");
        
        Date date; 
        date = new Date();
        
        jLabelbillingdate.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        jLabelbillingtime.setText(dtf.format(now));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelbillingdate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelbillingtime = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfbillingname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfbillingcontactno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfbillingemailid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfbillingaddress = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfbillingpid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfbillingpname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfbillingprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfbilingquantity = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfbillingdescription = new javax.swing.JTextField();
        btnbillingadd = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebilling = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tfbillingtotal = new javax.swing.JTextField();
        tfbillingpaid = new javax.swing.JTextField();
        tfbillingteturned = new javax.swing.JTextField();
        btnbillingprint = new javax.swing.JButton();
        btnbillingreset = new javax.swing.JButton();
        btnbillingclose = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/billing frame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date:-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 30, -1, -1));

        jLabelbillingdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelbillingdate.setText("jLabel4");
        getContentPane().add(jLabelbillingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Time:-");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 75, -1, -1));

        jLabelbillingtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelbillingtime.setText("jLabel6");
        getContentPane().add(jLabelbillingtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 75, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 1144, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Buyer Details :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 145, -1, -1));

        tfbillingname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingname, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 142, 188, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact No. :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 145, -1, -1));

        tfbillingcontactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingcontactnoActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 142, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email- Id. :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 145, -1, -1));

        tfbillingemailid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfbillingemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 142, 334, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Address :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 174, -1, -1));

        tfbillingaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfbillingaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 171, 877, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 1144, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Product Details :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Product Id. :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 226, -1, -1));

        tfbillingpid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingpidActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 223, 57, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Product Name :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 226, -1, -1));

        tfbillingpname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingpnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 223, 212, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Price :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 226, -1, -1));

        tfbillingprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfbillingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 223, 72, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Quantity :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 255, -1, -1));

        tfbilingquantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbilingquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbilingquantityActionPerformed(evt);
            }
        });
        getContentPane().add(tfbilingquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 252, 40, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Description :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 255, -1, -1));

        tfbillingdescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingdescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 252, 422, -1));

        btnbillingadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbillingadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/add.png"))); // NOI18N
        btnbillingadd.setText("Add");
        btnbillingadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnbillingadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 233, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, 1144, 10));

        tablebilling.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablebilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "DESCRIPTION", "RATE", "QUANTITY", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tablebilling);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, 700, 237));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Calculation :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 302, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Total Amount. :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 342, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Paid Amount. :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 387, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Returned Amount. :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 432, -1, -1));

        tfbillingtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingtotalActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 342, 118, -1));

        tfbillingpaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfbillingpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbillingpaidActionPerformed(evt);
            }
        });
        getContentPane().add(tfbillingpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 387, 118, -1));

        tfbillingteturned.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfbillingteturned, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 432, 118, -1));

        btnbillingprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbillingprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/print.png"))); // NOI18N
        btnbillingprint.setText("Print");
        btnbillingprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnbillingprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 489, -1, -1));

        btnbillingreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbillingreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        btnbillingreset.setText("Reset");
        btnbillingreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnbillingreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 489, -1, -1));

        btnbillingclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbillingclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        btnbillingclose.setText("Close");
        btnbillingclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillingcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnbillingclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 489, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/billing background.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1170, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfbillingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingnameActionPerformed
                     String name = tfbillingname.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select * from customr where name like '"+name+"%'");
              if(rs.next())
              {
                  tfbillingname.setText(rs.getString(2));
                  tfbillingcontactno.setText(rs.getString(4));
                  tfbillingemailid.setText(rs.getString(5));
                  tfbillingaddress.setText(rs.getString(3));
                  
                  
                 // tfupdatecontact.setEditable(false);
              }
              else {
                   tfbillingname.setText("");
                  tfbillingcontactno.setText("");
                  tfbillingemailid.setText("");
                  tfbillingaddress.setText("");
              }      
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_tfbillingnameActionPerformed

    private void tfbillingcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingcontactnoActionPerformed
        String contactno = tfbillingcontactno.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select * from customr where contactNo like  '"+contactno+"%'");
              if(rs.next())
              {
                  tfbillingname.setText(rs.getString(2));
                  tfbillingcontactno.setText(rs.getString(4));
                  tfbillingemailid.setText(rs.getString(5));
                  tfbillingaddress.setText(rs.getString(3));
                  
                 // tfupdatecontact.setEditable(false);ddd
              }
              else {
                   tfbillingname.setText("");
                  tfbillingcontactno.setText("");
                  tfbillingemailid.setText("");
                  tfbillingaddress.setText("");
              }      
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_tfbillingcontactnoActionPerformed

    private void tfbillingpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingpidActionPerformed
        String pid = tfbillingpid.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select *from product1 where pId ='"+pid+"'");
              if(rs.next())
              {
                  tfbillingpid.setText(rs.getString(1));
                  tfbillingpname.setText(rs.getString(2));
                  tfbillingprice.setText(rs.getString(3));
                  tfbillingdescription.setText(rs.getString(4));
                  tfbilingquantity.setText("1");
                  
                  
                 // tfupdatecontact.setEditable(false);ddd
              }
              else {
                   tfbillingpid.setText("");
                  tfbillingpname.setText("");
                  tfbillingprice.setText("");
                  tfbillingdescription.setText("");
                  tfbilingquantity.setText("");
              }     
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_tfbillingpidActionPerformed

    private void tfbilingquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbilingquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbilingquantityActionPerformed

    private void btnbillingcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingcloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnbillingcloseActionPerformed

    private void btnbillingresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingresetActionPerformed
        this.setVisible(false);
        new Billing().setVisible(true);
    }//GEN-LAST:event_btnbillingresetActionPerformed

    private void tfbillingpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingpnameActionPerformed
         String pname = tfbillingpname.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select *from product1 where pName like '"+pname+"%'");
              if(rs.next())
              {
                  tfbillingpid.setText(rs.getString(1));
                  tfbillingpname.setText(rs.getString(2));
                  tfbillingprice.setText(rs.getString(3));
                  tfbillingdescription.setText(rs.getString(4));
                  tfbilingquantity.setText("1"); 
                  
                 // tfupdatecontact.setEditable(false);ddd
              }
              else {
                   tfbillingpid.setText("");
                  tfbillingpname.setText("");
                  tfbillingprice.setText("");
                  tfbillingdescription.setText("");
                  tfbilingquantity.setText("");  
              }    
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_tfbillingpnameActionPerformed

    private void tfbillingdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingdescriptionActionPerformed
        String pdescription = tfbillingdescription.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select *from product1 where pDescription like '"+pdescription+"%'");
              if(rs.next())
              {
                  tfbillingpid.setText(rs.getString(1));
                  tfbillingpname.setText(rs.getString(2));
                  tfbillingprice.setText(rs.getString(3));
                  tfbillingdescription.setText(rs.getString(4));
                  tfbilingquantity.setText("1");
                  
                 // tfupdatecontact.setEditable(false);ddd
              }
              else {
                   tfbillingpid.setText("");
                  tfbillingpname.setText("");
                  tfbillingprice.setText("");
                  tfbillingdescription.setText("");
                  tfbilingquantity.setText("");
              }      
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          }
    }//GEN-LAST:event_tfbillingdescriptionActionPerformed

    private void btnbillingaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingaddActionPerformed
        int price = Integer.parseInt(tfbillingprice.getText());
        int quantity = Integer.parseInt(tfbilingquantity.getText());
        int total = price+quantity;
        DefaultTableModel model =(DefaultTableModel)tablebilling.getModel();
   
        model.addRow(new Object[]{tfbillingpname.getText(),tfbillingdescription.getText(),price,quantity,total}) ;
        finalTotal=finalTotal+total;
        String finalTotal1 = String.valueOf(finalTotal);
        tfbillingtotal.setText(finalTotal1);
        
        
        
    }//GEN-LAST:event_btnbillingaddActionPerformed

    private void tfbillingtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingtotalActionPerformed
       
    }//GEN-LAST:event_tfbillingtotalActionPerformed

    private void tfbillingpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbillingpaidActionPerformed
         String paidAmaount = tfbillingpaid.getText();
        int paidamaount1=Integer.parseInt(paidAmaount);
        finalTotal=paidamaount1-finalTotal;
        String finalTotal1=String.valueOf(finalTotal);
        tfbillingteturned.setText(finalTotal1);
        tfbillingteturned.setEditable(false);
    }//GEN-LAST:event_tfbillingpaidActionPerformed

    private void btnbillingprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillingprintActionPerformed
            String name = tfbillingname.getText();
            String contactNo = tfbillingcontactno.getText();
            String email = tfbillingemailid.getText();
            String address = tfbillingaddress.getText();
            String path = "C:\\aMY PC\\Saket\\Project\\billing_Management_System\\BillingManagementSystem";//D:\\saket\\Programming\\Java\\Project\\billing_Management_System\\BillingManagementSystem\\
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try{
                
                PdfWriter.getInstance(doc, new FileOutputStream(path+""+name+""+jLabelbillingdate.getText()+".pdf"));//""+jLabelbillingtime.getText()+
                doc.open();
                Paragraph paragraph1 = new Paragraph("                                                 SAKET'S BILING MANAGEMENT SYSTEM\n                                                        Contact No.: 8210413097\n\n");
                doc.add(paragraph1);
                Paragraph paragraph2 = new Paragraph("Date & Time Of Order:- "+jLabelbillingdate.getText()+"   "+jLabelbillingtime.getText()+"\nBuyer Details:-\n      Name:- "+name+"\n      Contact No.:- "+contactNo+"\n      Email Id.:- "+email+"\n      Address:- "+address+"\n\n");
                doc.add(paragraph2);
                PdfPTable tb1 = new PdfPTable(5);
                tb1.addCell("Name");    
                tb1.addCell("Description");
                tb1.addCell("Rate");
                tb1.addCell("Quantity");
                tb1.addCell("Sub Total");
                for(int i=0;i<tablebilling.getRowCount();i++)
                {
                    String a =  tablebilling.getValueAt(i, 0).toString();
                    String b =  tablebilling.getValueAt(i, 1).toString();
                    String c =  tablebilling.getValueAt(i, 2).toString();
                    String d =  tablebilling.getValueAt(i, 3).toString();
                    String e =  tablebilling.getValueAt(i, 4).toString();
                    tb1.addCell(a);
                    tb1.addCell(b);
                    tb1.addCell(c);
                    tb1.addCell(d);
                    tb1.addCell(e);
                }
                doc.add(tb1);
                Paragraph paragraph3 = new Paragraph("\n    Total Amount:- Rs."+tfbillingtotal.getText()+"\n    Paid Amount:- Rs."+tfbillingpaid.getText()+"\n    Returned Amount:- Rs."+tfbillingteturned.getText()+"\n\n    Thank You For Shopping With Us ! \n    Please Visit Again!! (:");
                
                doc.add(paragraph3);
                JOptionPane.showMessageDialog(null, "Bill Generated !");
                setVisible(true);
                new Billing().setVisible(true);
                
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        doc.close();
            
    }//GEN-LAST:event_btnbillingprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbillingadd;
    private javax.swing.JButton btnbillingclose;
    private javax.swing.JButton btnbillingprint;
    private javax.swing.JButton btnbillingreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelbillingdate;
    private javax.swing.JLabel jLabelbillingtime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tablebilling;
    private javax.swing.JTextField tfbilingquantity;
    private javax.swing.JTextField tfbillingaddress;
    private javax.swing.JTextField tfbillingcontactno;
    private javax.swing.JTextField tfbillingdescription;
    private javax.swing.JTextField tfbillingemailid;
    private javax.swing.JTextField tfbillingname;
    private javax.swing.JTextField tfbillingpaid;
    private javax.swing.JTextField tfbillingpid;
    private javax.swing.JTextField tfbillingpname;
    private javax.swing.JTextField tfbillingprice;
    private javax.swing.JTextField tfbillingteturned;
    private javax.swing.JTextField tfbillingtotal;
    // End of variables declaration//GEN-END:variables
}
