/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;

import Project.connectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Saket Saurabh
 */
public class DeleteCustomer extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCustomer
     */
    public DeleteCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletecustomersearchbtn = new javax.swing.JButton();
        deletecustomertfsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        deletebuyerlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfdeletename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdeletecontact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdeleteemailid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdeleteaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboboxdeletegender = new javax.swing.JComboBox();
        customerdeletebtn = new javax.swing.JButton();
        customerdeleteresetbtn = new javax.swing.JButton();
        customerdelteclosebtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deletecustomersearchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletecustomersearchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/search.png"))); // NOI18N
        deletecustomersearchbtn.setText("Search");
        deletecustomersearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecustomersearchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletecustomersearchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 98, -1, -1));

        deletecustomertfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecustomertfsearchActionPerformed(evt);
            }
        });
        getContentPane().add(deletecustomertfsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 100, 162, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        deletebuyerlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/delete buyer.png"))); // NOI18N
        getContentPane().add(deletebuyerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Delete buyer ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 580, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        tfdeletename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeletename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeletenameActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeletename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 323, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contact No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        tfdeletecontact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfdeletecontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 323, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("E-Mail Id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        tfdeleteemailid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeleteemailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeleteemailidActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeleteemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 323, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        tfdeleteaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeleteaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeleteaddressActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeleteaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 323, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        comboboxdeletegender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxdeletegender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Prefer Not To Say" }));
        getContentPane().add(comboboxdeletegender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        customerdeletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerdeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/delete.png"))); // NOI18N
        customerdeletebtn.setText("Delete");
        customerdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        customerdeleteresetbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerdeleteresetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        customerdeleteresetbtn.setText("Reset");
        customerdeleteresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdeleteresetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerdeleteresetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        customerdelteclosebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerdelteclosebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        customerdelteclosebtn.setText("Close");
        customerdelteclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerdelteclosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerdelteclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, 590, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletecustomersearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecustomersearchbtnActionPerformed

        String contactNo = deletecustomertfsearch.getText();
        try{
            Connection con=connectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select *from customr where mobNo =  '"+contactNo+"'");
            if(rs.next())
            {
                tfdeletename.setText(rs.getString(2));
                tfdeletename.setEditable(false);
                tfdeletecontact.setText(rs.getString(4));
                tfdeletecontact.setEditable(false);
                tfdeleteemailid.setText(rs.getString(5));
                tfdeleteemailid.setEditable(false);
                tfdeleteaddress.setText(rs.getString(3));
                tfdeleteaddress.setEditable(false);
                comboboxdeletegender.setSelectedItem(rs.getString(6));
                comboboxdeletegender.setEditable(false);

                // tfupdatecontact.setEditable(false);
            }
            else {
                JOptionPane.showMessageDialog(null,"Contact No. Does Not exist !");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deletecustomersearchbtnActionPerformed

    private void deletecustomertfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecustomertfsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletecustomertfsearchActionPerformed

    private void tfdeletenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeletenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeletenameActionPerformed

    private void tfdeleteemailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeleteemailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeleteemailidActionPerformed

    private void tfdeleteaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeleteaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeleteaddressActionPerformed

    private void customerdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdeletebtnActionPerformed
        String contactNoold = deletecustomertfsearch.getText();
        String name = tfdeletename.getText();
        String contactNo = tfdeletecontact.getText();
        String email = tfdeleteemailid.getText();
        String address = tfdeleteaddress.getText();
        String gender = (String)comboboxdeletegender.getSelectedItem();
        try{
            Connection con=connectionProvider.getcon();
            Statement st=con.createStatement();//delete from customer where contactNo='a';
            st.executeUpdate("delete from customr where mobNo='"+contactNoold+"'");
            JOptionPane.showMessageDialog(null,"Successfully Deleted ");
            setVisible(false);
            new DeleteCustomer().setVisible(true);
    }//GEN-LAST:event_customerdeletebtnActionPerformed
        catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }
    
    private void customerdeleteresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdeleteresetbtnActionPerformed
        this.setVisible(false);
        new DeleteCustomer().setVisible(true);
    }//GEN-LAST:event_customerdeleteresetbtnActionPerformed

    private void customerdelteclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerdelteclosebtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_customerdelteclosebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboboxdeletegender;
    private javax.swing.JButton customerdeletebtn;
    private javax.swing.JButton customerdeleteresetbtn;
    private javax.swing.JButton customerdelteclosebtn;
    private javax.swing.JLabel deletebuyerlabel;
    private javax.swing.JButton deletecustomersearchbtn;
    private javax.swing.JTextField deletecustomertfsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField tfdeleteaddress;
    private javax.swing.JTextField tfdeletecontact;
    private javax.swing.JTextField tfdeleteemailid;
    private javax.swing.JTextField tfdeletename;
    // End of variables declaration//GEN-END:variables
}
