/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;
import Project.connectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Saket Saurabh
 */
public class DeleteProduct extends javax.swing.JFrame {

    /**
     * Creates new form DeleteProduct
     */
    public DeleteProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfdeleteproductsearch = new javax.swing.JTextField();
        deleteproductbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfdeleteproductname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdeleteproductprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdeleteproductdescription = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboboxudeleteproductcategory = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboboxdeleteproductstatus = new javax.swing.JComboBox();
        btnDeleteproductupdate = new javax.swing.JButton();
        btnupdateproductreset = new javax.swing.JButton();
        btnupdateproductclose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/delete product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/delete product ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Id :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 93, -1, -1));

        tfdeleteproductsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeleteproductsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeleteproductsearchActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeleteproductsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 93, 100, -1));

        deleteproductbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteproductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/search.png"))); // NOI18N
        deleteproductbtn.setText("Seacrh");
        deleteproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteproductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 87, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 157, -1, -1));

        tfdeleteproductname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeleteproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeleteproductnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeleteproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 154, 249, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 198, -1, -1));

        tfdeleteproductprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfdeleteproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 195, 249, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 239, -1, -1));

        tfdeleteproductdescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfdeleteproductdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdeleteproductdescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tfdeleteproductdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 236, 249, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 280, -1, -1));

        comboboxudeleteproductcategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxudeleteproductcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baverages", "Bread & Bakery", "Cereals", "soups & Cleaner", "spices", "Dairy", "Health & Beauty", "Miscellaneous" }));
        getContentPane().add(comboboxudeleteproductcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 277, 116, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 321, -1, -1));

        comboboxdeleteproductstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxdeleteproductstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        comboboxdeleteproductstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxdeleteproductstatusActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxdeleteproductstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 318, 116, -1));

        btnDeleteproductupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteproductupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/delete.png"))); // NOI18N
        btnDeleteproductupdate.setText("Delete");
        btnDeleteproductupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteproductupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteproductupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        btnupdateproductreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateproductreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        btnupdateproductreset.setText("Reset");
        btnupdateproductreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproductreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        btnupdateproductclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateproductclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        btnupdateproductclose.setText("Close");
        btnupdateproductclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproductclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 580, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 580, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 361, 580, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdeleteproductsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeleteproductsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeleteproductsearchActionPerformed

    private void deleteproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproductbtnActionPerformed
        String pId = tfdeleteproductsearch.getText();
        try{
            Connection con=connectionProvider.getcon();
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select *from product where pId =  '"+pId+"'");
            if(rs.next())
            {
                tfdeleteproductname.setText(rs.getString(2));
                tfdeleteproductprice.setText(rs.getString(3));
                tfdeleteproductdescription.setText(rs.getString(4));
                comboboxudeleteproductcategory.setSelectedItem(rs.getString(5));
                comboboxdeleteproductstatus.setSelectedItem(rs.getString(6));

                // tfupdatecontact.setEditable(false);
            }
            else {
                JOptionPane.showMessageDialog(null,"Product Does Not exist !");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_deleteproductbtnActionPerformed

    private void tfdeleteproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeleteproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeleteproductnameActionPerformed

    private void tfdeleteproductdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdeleteproductdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdeleteproductdescriptionActionPerformed

    private void btnDeleteproductupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteproductupdateActionPerformed
        String pId = tfdeleteproductsearch.getText();
        String pName = tfdeleteproductname.getText();
        String pPrice = tfdeleteproductprice.getText();
        String pDescription = tfdeleteproductdescription.getText();
        String pCategory = (String)comboboxudeleteproductcategory.getSelectedItem();
        String pStatus = (String)comboboxdeleteproductstatus.getSelectedItem();
        try{
            Connection con=connectionProvider.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from product where pId='"+pId+"'");
            JOptionPane.showMessageDialog(null,"Successfully Deleted ");
            setVisible(false);
            new DeleteProduct().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnDeleteproductupdateActionPerformed

    private void btnupdateproductresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductresetActionPerformed
        this.setVisible(false);
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnupdateproductresetActionPerformed

    private void btnupdateproductcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductcloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnupdateproductcloseActionPerformed

    private void comboboxdeleteproductstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxdeleteproductstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxdeleteproductstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteproductupdate;
    private javax.swing.JButton btnupdateproductclose;
    private javax.swing.JButton btnupdateproductreset;
    private javax.swing.JComboBox comboboxdeleteproductstatus;
    private javax.swing.JComboBox comboboxudeleteproductcategory;
    private javax.swing.JButton deleteproductbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField tfdeleteproductdescription;
    private javax.swing.JTextField tfdeleteproductname;
    private javax.swing.JTextField tfdeleteproductprice;
    private javax.swing.JTextField tfdeleteproductsearch;
    // End of variables declaration//GEN-END:variables
}
