/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;

import Project.connectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Saket Saurabh
 */
public class NewProduct extends javax.swing.JFrame {

    /**
     * Creates new form NewProduct
     */
    public NewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        labelnewproductid = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfnewproductname = new javax.swing.JTextField();
        tfnewproductprice = new javax.swing.JTextField();
        tfnewproductdescription = new javax.swing.JTextField();
        comboboxnewproductcategory = new javax.swing.JComboBox();
        comboboxnewproductstatus = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        btnaddproduct = new javax.swing.JButton();
        btnnewproductreset = new javax.swing.JButton();
        btnnewproductclose = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/new product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/New Product ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 582, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Id :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 102, -1, -1));

        labelnewproductid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelnewproductid.setForeground(new java.awt.Color(255, 0, 51));
        labelnewproductid.setText("100");
        getContentPane().add(labelnewproductid, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 98, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 582, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 157, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 198, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 239, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 321, -1, -1));

        tfnewproductname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfnewproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnewproductnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfnewproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 154, 249, -1));

        tfnewproductprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfnewproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 195, 249, -1));

        tfnewproductdescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfnewproductdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 236, 249, -1));

        comboboxnewproductcategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxnewproductcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baverages", "Bread & Bakery", "Cereals", "soups & Cleaner", "spices", "Dairy", "Health & Beauty", "Miscellaneous" }));
        getContentPane().add(comboboxnewproductcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 277, 116, -1));

        comboboxnewproductstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxnewproductstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        getContentPane().add(comboboxnewproductstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 318, 116, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, 582, 10));

        btnaddproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaddproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/add.png"))); // NOI18N
        btnaddproduct.setText("Add Product");
        btnaddproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 380, -1, -1));

        btnnewproductreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnewproductreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        btnnewproductreset.setText("Reset");
        btnnewproductreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproductreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 380, -1, -1));

        btnnewproductclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnewproductclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        btnnewproductclose.setText("Close");
        btnnewproductclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewproductcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnnewproductclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 380, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnewproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnewproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnewproductnameActionPerformed

    private void btnnewproductcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproductcloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnnewproductcloseActionPerformed

    private void btnnewproductresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewproductresetActionPerformed
        this.setVisible(false);
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_btnnewproductresetActionPerformed

    private void btnaddproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddproductActionPerformed
       
          String pId = labelnewproductid.getText();
          String pName = tfnewproductname.getText();
          String pPrice = tfnewproductprice.getText();
          String pDescription = tfnewproductdescription.getText();
          String pCategory = (String)comboboxnewproductcategory.getSelectedItem();
          String pStatus = (String)comboboxnewproductstatus.getSelectedItem();
          try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              st.executeUpdate("insert into product values('"+pId+"','"+pName+"','"+pPrice+"','"+pDescription+"','"+pCategory+"','"+pStatus+"')");
              JOptionPane.showMessageDialog(null,"Successfully added ");
              setVisible(false);
              new NewProduct().setVisible(true);
                      
          }
          catch(java.sql.SQLIntegrityConstraintViolationException e)
          {
            JOptionPane.showMessageDialog(null,"Successfully updated ");  
          }
          catch(Exception e)
          {
              
              JOptionPane.showMessageDialog(null,e);
          }
    }//GEN-LAST:event_btnaddproductActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
              Connection con=connectionProvider.getcon();
             // Statement st=con.createStatement();
              Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
              ResultSet rs = st.executeQuery("select max(pId) from product");
              if(rs.first())
              {
                  int id = rs.getInt(1);
                  id=id+1;
                  String str = String.valueOf(id);
                  labelnewproductid.setText(str);
              }
              else
              {
                  labelnewproductid.setText("1");
              }
        }
          catch (Exception e)
                {
                JOptionPane.showMessageDialog(null,e);
                }          
        
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddproduct;
    private javax.swing.JButton btnnewproductclose;
    private javax.swing.JButton btnnewproductreset;
    private javax.swing.JComboBox comboboxnewproductcategory;
    private javax.swing.JComboBox comboboxnewproductstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelnewproductid;
    private javax.swing.JTextField tfnewproductdescription;
    private javax.swing.JTextField tfnewproductname;
    private javax.swing.JTextField tfnewproductprice;
    // End of variables declaration//GEN-END:variables
}
