/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;

import Project.connectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Saket Saurabh
 */
public class UpdateProduct extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tfupdateproductsearch = new javax.swing.JTextField();
        updateproductbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tfupdateproductname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfupdateproductprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfupdateproductdescription = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboboxupdateproductcategory = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comboboxupdateproductstatus = new javax.swing.JComboBox();
        btnupdateproductreset = new javax.swing.JButton();
        btnupdateproductclose = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnupdateproductupdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/update product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/update product ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Id :-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 93, -1, -1));

        tfupdateproductsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdateproductsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdateproductsearchActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdateproductsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 93, 100, -1));

        updateproductbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateproductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/search.png"))); // NOI18N
        updateproductbtn.setText("Seacrh");
        updateproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateproductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateproductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 87, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 580, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 157, -1, -1));

        tfupdateproductname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdateproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdateproductnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdateproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 154, 249, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 198, -1, -1));

        tfupdateproductprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfupdateproductprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 195, 249, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 239, -1, -1));

        tfupdateproductdescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdateproductdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdateproductdescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdateproductdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 236, 249, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 280, -1, -1));

        comboboxupdateproductcategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxupdateproductcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baverages", "Bread & Bakery", "Cereals", "soups & Cleaner", "spices", "Dairy", "Health & Beauty", "Miscellaneous" }));
        getContentPane().add(comboboxupdateproductcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 277, 116, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Status");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 321, -1, -1));

        comboboxupdateproductstatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxupdateproductstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive" }));
        getContentPane().add(comboboxupdateproductstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 318, 116, -1));

        btnupdateproductreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateproductreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        btnupdateproductreset.setText("Reset");
        btnupdateproductreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproductreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        btnupdateproductclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateproductclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        btnupdateproductclose.setText("Close");
        btnupdateproductclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproductclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 352, 582, 10));

        btnupdateproductupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdateproductupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/save.png"))); // NOI18N
        btnupdateproductupdate.setText("Update");
        btnupdateproductupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateproductupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdateproductupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfupdateproductsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdateproductsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdateproductsearchActionPerformed

    private void updateproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateproductbtnActionPerformed
         String pId = tfupdateproductsearch.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select *from product where pId =  '"+pId+"'");
              if(rs.next())
              {
                  tfupdateproductname.setText(rs.getString(2));
                  tfupdateproductprice.setText(rs.getString(3));
                  tfupdateproductdescription.setText(rs.getString(4));
                  comboboxupdateproductcategory.setSelectedItem(rs.getString(5));
                  comboboxupdateproductstatus.setSelectedItem(rs.getString(6));
                  
                 // tfupdatecontact.setEditable(false);
              }
              else {
                  JOptionPane.showMessageDialog(null,"Product Does Not exist !");
              }      
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_updateproductbtnActionPerformed

    private void tfupdateproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdateproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdateproductnameActionPerformed

    private void btnupdateproductresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductresetActionPerformed
        this.setVisible(false);
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_btnupdateproductresetActionPerformed

    private void btnupdateproductcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductcloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnupdateproductcloseActionPerformed

    private void tfupdateproductdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdateproductdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdateproductdescriptionActionPerformed

    private void btnupdateproductupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateproductupdateActionPerformed
             String pId = tfupdateproductsearch.getText();
          String pName = tfupdateproductname.getText();
          String pPrice = tfupdateproductprice.getText();
          String pDescription = tfupdateproductdescription.getText();     
          String pCategory = (String)comboboxupdateproductcategory.getSelectedItem();
          String pStatus = (String)comboboxupdateproductstatus.getSelectedItem();
          try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              st.executeUpdate("update product set pName='"+pName+"',pPrice='"+pPrice+"',pDescription='"+pDescription+"',pCategory='"+pCategory+"',pStatus='"+pStatus+"' where pId='"+pId+"'");
              JOptionPane.showMessageDialog(null,"Successfully updated ");
              setVisible(false);
              new UpdateProduct().setVisible(true);
    }                                         
              catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_btnupdateproductupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdateproductclose;
    private javax.swing.JButton btnupdateproductreset;
    private javax.swing.JButton btnupdateproductupdate;
    private javax.swing.JComboBox comboboxupdateproductcategory;
    private javax.swing.JComboBox comboboxupdateproductstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField tfupdateproductdescription;
    private javax.swing.JTextField tfupdateproductname;
    private javax.swing.JTextField tfupdateproductprice;
    private javax.swing.JTextField tfupdateproductsearch;
    private javax.swing.JButton updateproductbtn;
    // End of variables declaration//GEN-END:variables
}
