/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingmanagementsystem;

import Project.connectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Saket Saurabh
 */
public class UpdateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form updatecustomer
     */
    public UpdateCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        tfsearch = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tfupdatename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfupdatecontact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfupdaeemailid = new javax.swing.JTextField();
        tfupdateaddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboboxupdategender = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        updateresetbtn = new javax.swing.JButton();
        updateclosebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Update buyer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/update buyer ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 580, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        tfsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsearchActionPerformed(evt);
            }
        });
        getContentPane().add(tfsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 100, 162, 29));

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/search.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 98, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        tfupdatename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdatenameActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 323, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Contact No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        tfupdatecontact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(tfupdatecontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 323, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("E-Mail Id");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        tfupdaeemailid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdaeemailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdaeemailidActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdaeemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 323, -1));

        tfupdateaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfupdateaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfupdateaddressActionPerformed(evt);
            }
        });
        getContentPane().add(tfupdateaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 323, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        comboboxupdategender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboboxupdategender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Prefer Not To Say" }));
        getContentPane().add(comboboxupdategender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, 590, 10));

        updateresetbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateresetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/Reset.png"))); // NOI18N
        updateresetbtn.setText("Reset");
        updateresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateresetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateresetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        updateclosebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateclosebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/close Jframe.png"))); // NOI18N
        updateclosebtn.setText("Close");
        updateclosebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateclosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateclosebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/add.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingmanagementsystem/resources/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsearchActionPerformed

    private void tfupdatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdatenameActionPerformed

    private void tfupdaeemailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdaeemailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdaeemailidActionPerformed

    private void updateresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateresetbtnActionPerformed
        this.setVisible(false);
        new NewCustomer().setVisible(true);
    }//GEN-LAST:event_updateresetbtnActionPerformed

    private void updateclosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateclosebtnActionPerformed
        this.setVisible(false);

    }//GEN-LAST:event_updateclosebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
          String contactNoold = tfsearch.getText();
          String name = tfupdatename.getText();
          String contactNo = tfupdatecontact.getText();     
          String email = tfupdaeemailid.getText();
          String address = tfupdateaddress.getText();
          String gender = (String)comboboxupdategender.getSelectedItem();
          try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              st.executeUpdate("update customer set name='"+name+"',contactNo='"+contactNo+"',email='"+email+"',address='"+address+"',gender='"+gender+"' where contactNo='"+contactNoold+"'");
              JOptionPane.showMessageDialog(null,"Successfully updated ");
              setVisible(false);
              new UpdateCustomer().setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed
              catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
       
           String contactNo = tfsearch.getText();
           try{
              Connection con=connectionProvider.getcon();
              Statement st=con.createStatement();
              ResultSet rs = st.executeQuery("select *from customer where contactNo =  '"+contactNo+"'");
              if(rs.next())
              {
                  tfupdatename.setText(rs.getString(1));
                  tfupdatecontact.setText(rs.getString(2));
                  tfupdaeemailid.setText(rs.getString(3));
                  tfupdateaddress.setText(rs.getString(4));
                  comboboxupdategender.setSelectedItem(rs.getString(5));
                  
                 // tfupdatecontact.setEditable(false);
              }
              else {
                  JOptionPane.showMessageDialog(null,"Contact No. Does Not exist !");
              }      
          }
          catch(Exception e)
          {
            JOptionPane.showMessageDialog(null,e);  
          } 
    }//GEN-LAST:event_searchbtnActionPerformed

    private void tfupdateaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfupdateaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfupdateaddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboboxupdategender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField tfsearch;
    private javax.swing.JTextField tfupdaeemailid;
    private javax.swing.JTextField tfupdateaddress;
    private javax.swing.JTextField tfupdatecontact;
    private javax.swing.JTextField tfupdatename;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton updateclosebtn;
    private javax.swing.JButton updateresetbtn;
    // End of variables declaration//GEN-END:variables
}
